env:
    - BAZEL_VERSION='0.29.1'

sudo: true

before_install:
    - ./bazel_travis_toolbox/before_install.sh

script:
    - bazel build //...

deploy:
    provider: script
    script: bazel run deploy_www.dustintoff.com